filename_dict = {
    "a": "1_a.png",
    "i": "1_i.png",
    "u": "1_u.png",
    "e": "1_e.png",
    "o": "1_o.png",
    "ka": "2_ka.png",
    "ki": "2_ki.png",
    "ku": "2_ku.png",
    "ke": "2_ke.png",
    "ko": "2_ko.png",
    "sa": "3_sa.png",
    "shi": "3_shi.png",
    "si": "3_shi.png",
    "su": "3_su.png",
    "se": "3_se.png",
    "so": "3_so.png",
    "ta": "4_ta.png",
    "chi": "4_chi.png",
    "ti": "4_chi.png",
    "tsu": "4_chu.png",
    "tu": "4_chu.png",
    "te": "4_te.png",
    "to": "4_to.png",
    "na": "5_na.png",
    "ni": "5_ni.png",
    "nu": "5_nu.png",
    "ne": "5_ne.png",
    "no": "5_no.png",
    "ha": "6_ha.png",
    "hi": "6_hi.png",
    "fu": "6_fu.png",
    "hu": "6_fu.png",
    "he": "6_he.png",
    "ho": "6_ho.png",
    "ma": "7_ma.png",
    "mi": "7_mi.png",
    "mu": "7_mu.png",
    "me": "7_me.png",
    "mo": "7_mo.png",
    "ya": "8_ya.png",
    "yu": "8_yu.png",
    "yo": "8_yo.png",
    "ra": "9_ra.png",
    "ri": "9_ri.png",
    "ru": "9_ru.png",
    "re": "9_re.png",
    "ro": "9_ro.png",
    "wa": "0_wa.png",
    "wo": "0_wo.png",
    "n": "0_n.png",

    "zm": "0_ex_zm.png",
    "hzm": "0_ex_hzm.png",
    "lm": "0_ex_lm.png",
    "-": "0_ex_lm.png",
    "~": "0_ex_lm.png",

    "ga": ("2_ka.png", "0_ex_zm.png"),
    "gi": ("2_ki.png", "0_ex_zm.png"),
    "gu": ("2_ku.png", "0_ex_zm.png"),
    "ge": ("2_ke.png", "0_ex_zm.png"),
    "go": ("2_ko.png", "0_ex_zm.png"),
    "za": ("3_sa.png", "0_ex_zm.png"),
    "ji": ("3_shi.png", "0_ex_zm.png"),
    "zi": ("3_shi.png", "0_ex_zm.png"),
    "zu": ("3_su.png", "0_ex_zm.png"),
    "ze": ("3_se.png", "0_ex_zm.png"),
    "zo": ("3_so.png", "0_ex_zm.png"),
    "da": ("4_ta.png", "0_ex_zm.png"),
    "di": ("4_chi.png", "0_ex_zm.png"),
    "du": ("4_tsu.png", "0_ex_zm.png"),
    "de": ("4_te.png", "0_ex_zm.png"),
    "do": ("4_to.png", "0_ex_zm.png"),
    "ba": ("6_ha.png", "0_ex_zm.png"),
    "bi": ("6_hi.png", "0_ex_zm.png"),
    "bu": ("6_fu.png", "0_ex_zm.png"),
    "be": ("6_he.png", "0_ex_zm.png"),
    "bo": ("6_ho.png", "0_ex_zm.png"),
    "pa": ("6_ha.png", "0_ex_hzm.png"),
    "pi": ("6_hi.png", "0_ex_hzm.png"),
    "pu": ("6_fu.png", "0_ex_hzm.png"),
    "pe": ("6_he.png", "0_ex_hzm.png"),
    "po": ("6_ho.png", "0_ex_hzm.png"),
}
