filename_dict = {
    "a": "1_a.png",
    "i": "1_i.png",
    "u": "1_u.png",
    "e": "1_e.png",
    "o": "1_o.png",
    "あ": "1_a.png",
    "い": "1_i.png",
    "う": "1_u.png",
    "え": "1_e.png",
    "お": "1_o.png",
    "ア": "1_a.png",
    "イ": "1_i.png",
    "ウ": "1_u.png",
    "エ": "1_e.png",
    "オ": "1_o.png",

    "ka": "2_ka.png",
    "ki": "2_ki.png",
    "ku": "2_ku.png",
    "ke": "2_ke.png",
    "ko": "2_ko.png",
    "か": "2_ka.png",
    "き": "2_ki.png",
    "く": "2_ku.png",
    "け": "2_ke.png",
    "こ": "2_ko.png",
    "カ": "2_ka.png",
    "キ": "2_ki.png",
    "ク": "2_ku.png",
    "ケ": "2_ke.png",
    "コ": "2_ko.png",

    "sa": "3_sa.png",
    "shi": "3_shi.png",
    "si": "3_shi.png",
    "su": "3_su.png",
    "se": "3_se.png",
    "so": "3_so.png",
    "さ": "3_sa.png",
    "し": "3_shi.png",
    "す": "3_su.png",
    "せ": "3_se.png",
    "そ": "3_so.png",
    "サ": "3_sa.png",
    "シ": "3_shi.png",
    "ス": "3_su.png",
    "セ": "3_se.png",
    "ソ": "3_so.png",

    "ta": "4_ta.png",
    "chi": "4_chi.png",
    "ti": "4_chi.png",
    "tsu": "4_tsu.png",
    "tu": "4_tsu.png",
    "te": "4_te.png",
    "to": "4_to.png",
    "た": "4_ta.png",
    "ち": "4_chi.png",
    "つ": "4_tsu.png",
    "て": "4_te.png",
    "と": "4_to.png",
    "タ": "4_ta.png",
    "チ": "4_chi.png",
    "ツ": "4_tsu.png",
    "テ": "4_te.png",
    "ト": "4_to.png",

    "na": "5_na.png",
    "ni": "5_ni.png",
    "nu": "5_nu.png",
    "ne": "5_ne.png",
    "no": "5_no.png",
    "な": "5_na.png",
    "に": "5_ni.png",
    "ぬ": "5_nu.png",
    "ね": "5_ne.png",
    "の": "5_no.png",
    "ナ": "5_na.png",
    "ニ": "5_ni.png",
    "ヌ": "5_nu.png",
    "ネ": "5_ne.png",
    "ノ": "5_no.png",

    "ha": "6_ha.png",
    "hi": "6_hi.png",
    "fu": "6_fu.png",
    "hu": "6_fu.png",
    "he": "6_he.png",
    "ho": "6_ho.png",
    "は": "6_ha.png",
    "ひ": "6_hi.png",
    "ふ": "6_fu.png",
    "へ": "6_he.png",
    "ほ": "6_ho.png",
    "ハ": "6_ha.png",
    "ヒ": "6_hi.png",
    "フ": "6_fu.png",
    "ヘ": "6_he.png",
    "ホ": "6_ho.png",

    "ma": "7_ma.png",
    "mi": "7_mi.png",
    "mu": "7_mu.png",
    "me": "7_me.png",
    "mo": "7_mo.png",
    "ま": "7_ma.png",
    "み": "7_mi.png",
    "む": "7_mu.png",
    "め": "7_me.png",
    "も": "7_mo.png",
    "マ": "7_ma.png",
    "ミ": "7_mi.png",
    "ム": "7_mu.png",
    "メ": "7_me.png",
    "モ": "7_mo.png",

    "ya": "8_ya.png",
    "yu": "8_yu.png",
    "yo": "8_yo.png",
    "や": "8_ya.png",
    "ゆ": "8_yu.png",
    "よ": "8_yo.png",
    "ヤ": "8_ya.png",
    "ユ": "8_yu.png",
    "ヨ": "8_yo.png",

    "ra": "9_ra.png",
    "ri": "9_ri.png",
    "ru": "9_ru.png",
    "re": "9_re.png",
    "ro": "9_ro.png",
    "ら": "9_ra.png",
    "り": "9_ri.png",
    "る": "9_ru.png",
    "れ": "9_re.png",
    "ろ": "9_ro.png",
    "ラ": "9_ra.png",
    "リ": "9_ri.png",
    "ル": "9_ru.png",
    "レ": "9_re.png",
    "ロ": "9_ro.png",

    "wa": "0_wa.png",
    "wo": "0_wo.png",
    "n": "0_n.png",
    "わ": "0_wa.png",
    "を": "0_wo.png",
    "ん": "0_n.png",
    "ワ": "0_wa.png",
    "ヲ": "0_wo.png",
    "ン": "0_n.png",

    "zm": "0_ex_zm.png",  # 濁音符號
    "hzm": "0_ex_hzm.png",  # 半濁音符號
    "lm": "0_ex_lm.png",  # 長音符號
    "ー": "0_ex_lm.png",
    "-": "0_ex_lm.png",
    "~": "0_ex_lm.png",

    # 濁音半濁音
    "ga": ("2_ka.png", "0_ex_zm.png"),
    "gi": ("2_ki.png", "0_ex_zm.png"),
    "gu": ("2_ku.png", "0_ex_zm.png"),
    "ge": ("2_ke.png", "0_ex_zm.png"),
    "go": ("2_ko.png", "0_ex_zm.png"),
    "が": ("2_ka.png", "0_ex_zm.png"),
    "ぎ": ("2_ki.png", "0_ex_zm.png"),
    "ぐ": ("2_ku.png", "0_ex_zm.png"),
    "げ": ("2_ke.png", "0_ex_zm.png"),
    "ご": ("2_ko.png", "0_ex_zm.png"),
    "ガ": ("2_ka.png", "0_ex_zm.png"),
    "ギ": ("2_ki.png", "0_ex_zm.png"),
    "グ": ("2_ku.png", "0_ex_zm.png"),
    "ゲ": ("2_ke.png", "0_ex_zm.png"),
    "ゴ": ("2_ko.png", "0_ex_zm.png"),

    "za": ("3_sa.png", "0_ex_zm.png"),
    "ji": ("3_shi.png", "0_ex_zm.png"),
    "zi": ("3_shi.png", "0_ex_zm.png"),
    "zu": ("3_su.png", "0_ex_zm.png"),
    "ze": ("3_se.png", "0_ex_zm.png"),
    "zo": ("3_so.png", "0_ex_zm.png"),
    "ざ": ("3_sa.png", "0_ex_zm.png"),
    "じ": ("3_shi.png", "0_ex_zm.png"),
    "ず": ("3_su.png", "0_ex_zm.png"),
    "ぜ": ("3_se.png", "0_ex_zm.png"),
    "ぞ": ("3_so.png", "0_ex_zm.png"),
    "ザ": ("3_sa.png", "0_ex_zm.png"),
    "ジ": ("3_shi.png", "0_ex_zm.png"),
    "ズ": ("3_su.png", "0_ex_zm.png"),
    "ゼ": ("3_se.png", "0_ex_zm.png"),
    "ゾ": ("3_so.png", "0_ex_zm.png"),

    "da": ("4_ta.png", "0_ex_zm.png"),
    "di": ("4_chi.png", "0_ex_zm.png"),
    "du": ("4_tsu.png", "0_ex_zm.png"),
    "de": ("4_te.png", "0_ex_zm.png"),
    "do": ("4_to.png", "0_ex_zm.png"),
    "だ": ("4_ta.png", "0_ex_zm.png"),
    "ぢ": ("4_chi.png", "0_ex_zm.png"),
    "づ": ("4_tsu.png", "0_ex_zm.png"),
    "で": ("4_te.png", "0_ex_zm.png"),
    "ど": ("4_to.png", "0_ex_zm.png"),
    "ダ": ("4_ta.png", "0_ex_zm.png"),
    "ヂ": ("4_chi.png", "0_ex_zm.png"),
    "ヅ": ("4_tsu.png", "0_ex_zm.png"),
    "デ": ("4_te.png", "0_ex_zm.png"),
    "ド": ("4_to.png", "0_ex_zm.png"),

    "ba": ("6_ha.png", "0_ex_zm.png"),
    "bi": ("6_hi.png", "0_ex_zm.png"),
    "bu": ("6_fu.png", "0_ex_zm.png"),
    "be": ("6_he.png", "0_ex_zm.png"),
    "bo": ("6_ho.png", "0_ex_zm.png"),
    "ば": ("6_ha.png", "0_ex_zm.png"),
    "び": ("6_hi.png", "0_ex_zm.png"),
    "ぶ": ("6_fu.png", "0_ex_zm.png"),
    "べ": ("6_he.png", "0_ex_zm.png"),
    "ぼ": ("6_ho.png", "0_ex_zm.png"),
    "バ": ("6_ha.png", "0_ex_zm.png"),
    "ビ": ("6_hi.png", "0_ex_zm.png"),
    "ブ": ("6_fu.png", "0_ex_zm.png"),
    "ベ": ("6_he.png", "0_ex_zm.png"),
    "ボ": ("6_ho.png", "0_ex_zm.png"),

    "pa": ("6_ha.png", "0_ex_hzm.png"),
    "pi": ("6_hi.png", "0_ex_hzm.png"),
    "pu": ("6_fu.png", "0_ex_hzm.png"),
    "pe": ("6_he.png", "0_ex_hzm.png"),
    "po": ("6_ho.png", "0_ex_hzm.png"),
    "ぱ": ("6_ha.png", "0_ex_hzm.png"),
    "ぴ": ("6_hi.png", "0_ex_hzm.png"),
    "ぷ": ("6_fu.png", "0_ex_hzm.png"),
    "ぺ": ("6_he.png", "0_ex_hzm.png"),
    "ぽ": ("6_ho.png", "0_ex_hzm.png"),
    "パ": ("6_ha.png", "0_ex_hzm.png"),
    "ピ": ("6_hi.png", "0_ex_hzm.png"),
    "プ": ("6_fu.png", "0_ex_hzm.png"),
    "ペ": ("6_he.png", "0_ex_hzm.png"),
    "ポ": ("6_ho.png", "0_ex_hzm.png"),

    # 促音
    "la": "1_small_a.png",
    "xa": "1_small_a.png",
    "ぁ": "1_small_a.png",
    "ァ": "1_small_a.png",
    "li": "1_small_i.png",
    "xi": "1_small_i.png",
    "ぃ": "1_small_i.png",
    "ィ": "1_small_i.png",
    "lu": "1_small_u.png",
    "xu": "1_small_u.png",
    "ぅ": "1_small_u.png",
    "ゥ": "1_small_u.png",
    "le": "1_small_e.png",
    "xe": "1_small_e.png",
    "ぇ": "1_small_e.png",
    "ェ": "1_small_e.png",
    "lo": "1_small_o.png",
    "xo": "1_small_o.png",
    "ぉ": "1_small_o.png",
    "ォ": "1_small_o.png",
    "lya": "8_small_ya.png",
    "xya": "8_small_ya.png",
    "ゃ": "8_small_ya.png",
    "ャ": "8_small_ya.png",
    "lyu": "8_small_yu.png",
    "xyu": "8_small_yu.png",
    "ゅ": "8_small_yu.png",
    "ュ": "8_small_yu.png",
    "lyo": "8_small_yo.png",
    "xyo": "8_small_yo.png",
    "ょ": "8_small_yo.png",
    "ョ": "8_small_yo.png",
    "ltu": "4_small_tsu.png",
    "xtu": "4_small_tsu.png",
    "っ": "4_small_tsu.png",
    "ッ": "4_small_tsu.png",

    # 特殊符號
    ".": "10_dot.png",
    "dot": "10_dot.png"
}
